stages:
    - deploy
deploy-job:
    stage: deploy
    script:
    - echo "Deploying application..."
    - mkdir -p /var/www/project
    - cp index* /var/www/project
    - echo "Application successfully deployed."
    environment:
      name: staging
      url: https://easyyes-dev.com
    only:
    - master